name: flutter_test_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  provider: ^6.0.5
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  google_sign_in: ^5.4.4
  shared_preferences: ^2.0.17
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/map_styles/

flutter_intl:
  enabled: true

